# Generated by Django 5.0.1 on 2024-02-05 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaveapp', '0003_student_password_student_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='student',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
