# Generated by Django 5.0.1 on 2024-02-07 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaveapp', '0004_alter_leaverequest_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='department',
            new_name='t_department',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='teacher_name',
            new_name='t_name',
        ),
        migrations.AddField(
            model_name='teacher',
            name='t_email',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='t_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='t_password',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='t_username',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
