# Generated by Django 5.0.1 on 2024-02-07 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaveapp', '0005_rename_department_teacher_t_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='is_approval',
            field=models.BooleanField(default=False),
        ),
    ]
