# Generated by Django 5.0.1 on 2024-02-07 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaveapp', '0006_teacher_is_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='t_gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, null=True),
        ),
    ]
