# Generated by Django 5.0.1 on 2024-02-07 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaveapp', '0007_teacher_t_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='t_gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True),
        ),
    ]
